# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#ZSH_THEME="agnoster"
ZSH_THEME="powerlevel10k/powerlevel10k"
CASE_SENSITIVE="true"
HIST_STAMPS="dd/mm/yyyy"

# PowerLevel10k
## To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f $HOME/.p10k.zsh ]] || source $HOME/.p10k.zsh

## Highlight settings
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none
ZSH_HIGHLIGHT_STYLES[alias]='fg=magenta,bold'
ZSH_COLORIZE_STYLE="native"

# Oh-My-ZSH
export ZSH=$HOME/.oh-my-zsh
plugins=(
  alias-tips
  colored-man-pages
  colorize
  common-aliases
  cp
  docker
  extract
  fasd
  git
  history
  python
  rsync
  screen
  tmux
  zsh-completions
  zsh-syntax-highlighting
)
source $ZSH/oh-my-zsh.sh

# HomeShick
source "$HOME/.homesick/repos/homeshick/homeshick.sh"

# Rust
[[ ! -f $HOME/.cargo/env ]] || source $HOME/.cargo/env

# User configuration
export PATH=$HOME/bin:/usr/local/bin:$PATH
export TERM="xterm-256color"
export EDITOR='vim'
export MANPATH="/usr/local/man:$MANPATH"

